import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:admin_app/models/service_user.dart';
import 'package:admin_app/services/database_service.dart';

class SignUpScreen extends StatefulWidget {
  const SignUpScreen({super.key});

  @override
  State<SignUpScreen> createState() => _SignUpScreenState();
}

class _SignUpScreenState extends State<SignUpScreen> {
  final _formKey = GlobalKey<FormState>();
  final _service = DatabaseService(Supabase.instance.client);

  // Controllers for text fields
  final _nameController = TextEditingController();
  final _addressController = TextEditingController();
  final _notesController = TextEditingController();
  final _nhsNumberController = TextEditingController();
  final _gpNameController = TextEditingController();
  final _gpPhoneController = TextEditingController();
  final _familyContactNameController = TextEditingController();
  final _familyContactPhoneController = TextEditingController();
  final _familyContactRelationController = TextEditingController();
  final _familyContactEmailController = TextEditingController();
  final _emergencyContactNameController = TextEditingController();
  final _emergencyContactPhoneController = TextEditingController();
  final _emergencyContactRelationController = TextEditingController();
  final _allergyController = TextEditingController();
  final _medicationController = TextEditingController();
  final _dietaryController = TextEditingController();

  // State variables
  DateTime? _dateOfBirth;
  String _gender = 'Female';
  String _mobilityStatus = 'Mobile';
  bool _isActive = true;
  DateTime? _admissionDate;
  DateTime? _dischargeDate;
  List<String> _allergies = [];
  List<String> _medications = [];
  bool _loading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _addressController.dispose();
    _notesController.dispose();
    _nhsNumberController.dispose();
    _gpNameController.dispose();
    _gpPhoneController.dispose();
    _familyContactNameController.dispose();
    _familyContactPhoneController.dispose();
    _familyContactRelationController.dispose();
    _familyContactEmailController.dispose();
    _emergencyContactNameController.dispose();
    _emergencyContactPhoneController.dispose();
    _emergencyContactRelationController.dispose();
    _allergyController.dispose();
    _medicationController.dispose();
    _dietaryController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(DateTime? currentDate, Function(DateTime) onDateSelected) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: currentDate ?? DateTime.now(),
      firstDate: DateTime(1900),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null) {
      onDateSelected(picked);
    }
  }

  void _addAllergy() {
    if (_allergyController.text.trim().isNotEmpty) {
      setState(() {
        _allergies.add(_allergyController.text.trim());
        _allergyController.clear();
      });
    }
  }

  void _addMedication() {
    if (_medicationController.text.trim().isNotEmpty) {
      setState(() {
        _medications.add(_medicationController.text.trim());
        _medicationController.clear();
      });
    }
  }

  Future<void> _save() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _loading = true);
    try {
      // Build medication list
      final medicationList = _medications.map((m) => {'name': m, 'dosage': '', 'frequency': ''}).toList();

      // Build care plan with additional info
      final carePlan = <String, dynamic>{
        'mobility_status': _mobilityStatus,
        'dietary_requirements': _dietaryController.text.trim(),
        'admission_date': _admissionDate?.toIso8601String(),
        'discharge_date': _dischargeDate?.toIso8601String(),
        'allergies': _allergies,
      };

      final serviceUser = ServiceUser(
        id: '', // Will be generated by database
        name: _nameController.text.trim(),
        address: _addressController.text.trim(),
        notes: _notesController.text.trim().isNotEmpty ? _notesController.text.trim() : null,
        referenceCode: null,
        dateOfBirth: _dateOfBirth,
        nhsNumber: _nhsNumberController.text.trim().isNotEmpty ? _nhsNumberController.text.trim() : null,
        gpName: _gpNameController.text.trim().isNotEmpty ? _gpNameController.text.trim() : null,
        gpPhone: _gpPhoneController.text.trim().isNotEmpty ? _gpPhoneController.text.trim() : null,
        familyContactName: _familyContactNameController.text.trim().isNotEmpty ? _familyContactNameController.text.trim() : null,
        familyContactPhone: _familyContactPhoneController.text.trim().isNotEmpty ? _familyContactPhoneController.text.trim() : null,
        familyContactRelation: _familyContactRelationController.text.trim().isNotEmpty ? _familyContactRelationController.text.trim() : null,
        familyContactEmail: _familyContactEmailController.text.trim().isNotEmpty ? _familyContactEmailController.text.trim() : null,
        emergencyContactName: _emergencyContactNameController.text.trim().isNotEmpty ? _emergencyContactNameController.text.trim() : null,
        emergencyContactPhone: _emergencyContactPhoneController.text.trim().isNotEmpty ? _emergencyContactPhoneController.text.trim() : null,
        emergencyContactRelation: _emergencyContactRelationController.text.trim().isNotEmpty ? _emergencyContactRelationController.text.trim() : null,
        medicationList: medicationList,
        carePlan: carePlan,
        isActive: _isActive,
        createdAt: DateTime.now(),
      );

      await _service.addServiceUser(serviceUser);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Service user added successfully')),
        );
        Navigator.pop(context, true);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error adding service user: $e')),
        );
      }
    } finally {
      setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Service User'),
        backgroundColor: const Color(0xFF1565C0),
        foregroundColor: Colors.white,
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : Form(
              key: _formKey,
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  // Personal Information Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Personal Information',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _nameController,
                            decoration: const InputDecoration(
                              labelText: 'Full Name *',
                              border: OutlineInputBorder(),
                            ),
                            validator: (v) => v?.isEmpty ?? true ? 'Required' : null,
                          ),
                          const SizedBox(height: 12),
                          InkWell(
                            onTap: () => _selectDate(_dateOfBirth, (d) => setState(() => _dateOfBirth = d)),
                            child: InputDecorator(
                              decoration: const InputDecoration(
                                labelText: 'Date of Birth',
                                border: OutlineInputBorder(),
                              ),
                              child: Text(
                                _dateOfBirth != null
                                    ? _dateOfBirth!.toString().split(' ').first
                                    : 'Select date',
                              ),
                            ),
                          ),
                          const SizedBox(height: 12),
                          DropdownButtonFormField<String>(
                            value: _gender,
                            decoration: const InputDecoration(
                              labelText: 'Gender',
                              border: OutlineInputBorder(),
                            ),
                            items: ['Male', 'Female', 'Other', 'Prefer not to say']
                                .map((g) => DropdownMenuItem(value: g, child: Text(g)))
                                .toList(),
                            onChanged: (v) => setState(() => _gender = v!),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _nhsNumberController,
                            decoration: const InputDecoration(
                              labelText: 'NHS Number',
                              border: OutlineInputBorder(),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Contact Information Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Contact Information',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _addressController,
                            decoration: const InputDecoration(
                              labelText: 'Address',
                              border: OutlineInputBorder(),
                            ),
                            maxLines: 3,
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // GP Details Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'GP Details',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _gpNameController,
                            decoration: const InputDecoration(
                              labelText: 'GP Name',
                              border: OutlineInputBorder(),
                            ),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _gpPhoneController,
                            decoration: const InputDecoration(
                              labelText: 'GP Phone',
                              border: OutlineInputBorder(),
                            ),
                            keyboardType: TextInputType.phone,
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Family Contact Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Family/Next of Kin Contact',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _familyContactNameController,
                            decoration: const InputDecoration(
                              labelText: 'Name',
                              border: OutlineInputBorder(),
                            ),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _familyContactRelationController,
                            decoration: const InputDecoration(
                              labelText: 'Relation',
                              border: OutlineInputBorder(),
                            ),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _familyContactPhoneController,
                            decoration: const InputDecoration(
                              labelText: 'Phone',
                              border: OutlineInputBorder(),
                            ),
                            keyboardType: TextInputType.phone,
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _familyContactEmailController,
                            decoration: const InputDecoration(
                              labelText: 'Email',
                              border: OutlineInputBorder(),
                            ),
                            keyboardType: TextInputType.emailAddress,
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Emergency Contact Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Emergency Contact',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _emergencyContactNameController,
                            decoration: const InputDecoration(
                              labelText: 'Name',
                              border: OutlineInputBorder(),
                            ),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _emergencyContactRelationController,
                            decoration: const InputDecoration(
                              labelText: 'Relation',
                              border: OutlineInputBorder(),
                            ),
                          ),
                          const SizedBox(height: 12),
                          TextFormField(
                            controller: _emergencyContactPhoneController,
                            decoration: const InputDecoration(
                              labelText: 'Phone',
                              border: OutlineInputBorder(),
                            ),
                            keyboardType: TextInputType.phone,
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Clinical Information Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Clinical Information',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          const Text('Allergies', style: TextStyle(fontWeight: FontWeight.w500)),
                          const SizedBox(height: 8),
                          Row(
                            children: [
                              Expanded(
                                child: TextFormField(
                                  controller: _allergyController,
                                  decoration: const InputDecoration(
                                    labelText: 'Add allergy',
                                    border: OutlineInputBorder(),
                                  ),
                                ),
                              ),
                              const SizedBox(width: 8),
                              ElevatedButton(
                                onPressed: _addAllergy,
                                child: const Text('Add'),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Wrap(
                            spacing: 8,
                            runSpacing: 4,
                            children: _allergies.map((allergy) => Chip(
                              label: Text(allergy),
                              onDeleted: () => setState(() => _allergies.remove(allergy)),
                            )).toList(),
                          ),
                          const SizedBox(height: 16),
                          const Text('Medications', style: TextStyle(fontWeight: FontWeight.w500)),
                          const SizedBox(height: 8),
                          Row(
                            children: [
                              Expanded(
                                child: TextFormField(
                                  controller: _medicationController,
                                  decoration: const InputDecoration(
                                    labelText: 'Add medication',
                                    border: OutlineInputBorder(),
                                  ),
                                ),
                              ),
                              const SizedBox(width: 8),
                              ElevatedButton(
                                onPressed: _addMedication,
                                child: const Text('Add'),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Wrap(
                            spacing: 8,
                            runSpacing: 4,
                            children: _medications.map((med) => Chip(
                              label: Text(med),
                              onDeleted: () => setState(() => _medications.remove(med)),
                            )).toList(),
                          ),
                          const SizedBox(height: 16),
                          TextFormField(
                            controller: _dietaryController,
                            decoration: const InputDecoration(
                              labelText: 'Dietary Requirements',
                              border: OutlineInputBorder(),
                            ),
                            maxLines: 2,
                          ),
                          const SizedBox(height: 12),
                          DropdownButtonFormField<String>(
                            value: _mobilityStatus,
                            decoration: const InputDecoration(
                              labelText: 'Mobility Status',
                              border: OutlineInputBorder(),
                            ),
                            items: ['Mobile', 'Requires Assistance', 'Unsteady', 'Wheelchair User', 'Bed Bound']
                                .map((s) => DropdownMenuItem(value: s, child: Text(s)))
                                .toList(),
                            onChanged: (v) => setState(() => _mobilityStatus = v!),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 16),

                  // Status Card
                  Card(
                    child: Padding(
                      padding: const EdgeInsets.all(16),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Status',
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                          ),
                          const SizedBox(height: 12),
                          SwitchListTile(
                            title: const Text('Active'),
                            subtitle: Text(_isActive ? 'Service user is active' : 'Service user is inactive'),
                            value: _isActive,
                            onChanged: (v) => setState(() => _isActive = v),
                          ),
                          const SizedBox(height: 12),
                          InkWell(
                            onTap: () => _selectDate(_admissionDate, (d) => setState(() => _admissionDate = d)),
                            child: InputDecorator(
                              decoration: const InputDecoration(
                                labelText: 'Admission Date',
                                border: OutlineInputBorder(),
                              ),
                              child: Text(
                                _admissionDate != null
                                    ? _admissionDate!.toString().split(' ').first
                                    : 'Select date',
                              ),
                            ),
                          ),
                          const SizedBox(height: 12),
                          InkWell(
                            onTap: () => _selectDate(_dischargeDate, (d) => setState(() => _dischargeDate = d)),
                            child: InputDecorator(
                              decoration: const InputDecoration(
                                labelText: 'Discharge Date (if applicable)',
                                border: OutlineInputBorder(),
                              ),
                              child: Text(
                                _dischargeDate != null
                                    ? _dischargeDate!.toString().split(' ').first
                                    : 'Select date',
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(height: 24),

                  // Save Button
                  SizedBox(
                    width: double.infinity,
                    child: ElevatedButton(
                      onPressed: _loading ? null : _save,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF1565C0),
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: const Text(
                        'Add Service User',
                        style: TextStyle(fontSize: 16),
                      ),
                    ),
                  ),
                  const SizedBox(height: 32),
                ],
              ),
            ),
    );
  }
}