-- Create fire_hazard_assessments table
CREATE TABLE fire_hazard_assessments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  service_user_id UUID,
  service_user_name TEXT,
  assessor_name TEXT,
  assessment_date DATE,
  risk_level TEXT,
  
  -- Your 50+ fields from the FireHazardAssessment model
  fire_warden_name TEXT,
  fire_alarm_system_type TEXT,
  smoke_detectors_present TEXT,
  fire_extinguisher_types TEXT[],  -- array of strings
  fire_alarm_test_date DATE,
  emergency_lighting_test_date DATE,
  fire_extinguisher_next_service_due DATE,
  fire_blanket_service_date DATE,
  staff_training_next_due DATE,
  pat_test_expiry_date DATE,
  fire_risk_assessment_review_date DATE,
  fire_alarm_weekly_test_recorded BOOLEAN,
  emergency_lighting_working BOOLEAN,
  fire_exit_signs_illuminated BOOLEAN,
  final_exits_open_outward BOOLEAN,
  escape_routes_suitable_for_mobility_aids BOOLEAN,
  peeps_reviewed_annually BOOLEAN,
  evacuation_plan_rehearsed BOOLEAN,
  visitors_signed_in_out BOOLEAN,
  night_staff_numbers_adequate BOOLEAN,
  disabled_refuge_points_identified BOOLEAN,
  staff_fire_training_completed BOOLEAN,
  fire_drill_conducted BOOLEAN,
  fire_warden_appointed BOOLEAN,
  fire_extinguisher_locations_documented BOOLEAN,
  equipment_inspected_monthly BOOLEAN,
  heat_detectors_in_kitchens BOOLEAN,
  fire_blanket_in_kitchen BOOLEAN,
  fire_hose_reel_present BOOLEAN,
  cooker_isolator_switch_accessible BOOLEAN,
  pat_testing_up_to_date BOOLEAN,
  staff_know_peeps_for_assigned_service_users BOOLEAN,
  evacuation_plan_displayed BOOLEAN,
  fire_log_book_maintained BOOLEAN,
  weekly_checks_recorded BOOLEAN,
  monthly_checks_recorded BOOLEAN,
  kitchen_extractor_hood_cleaned BOOLEAN,
  laundry_dryer_lint_filter_cleaned BOOLEAN,
  electrical_equipment_not_overloaded BOOLEAN,
  charging_devices_on_non_flammable_surface BOOLEAN,
  external_waste_bins_away_from_building BOOLEAN,
  bin_stores_locked BOOLEAN,
  external_lighting_working BOOLEAN,
  intruder_alarm_working BOOLEAN,
  fire_doors_self_closing BOOLEAN,
  fire_door_gaps_less_than_4mm BOOLEAN,
  fire_door_seals_intact BOOLEAN,
  compartment_walls_intact BOOLEAN,
  ceiling_floor_penetrations_sealed BOOLEAN,
  emergency_exits_clearly_marked BOOLEAN,
  exit_doors_open_easily BOOLEAN,
  exit_routes_unobstructed BOOLEAN,
  fire_drill_frequency TEXT,
  peeps_in_place_for_all_service_users TEXT,
  total_score INT,
  action_required TEXT,
  action_items JSONB,
  responsible_person TEXT,
  completion_deadline DATE,
  review_date DATE,
  signature_data TEXT,
  status TEXT DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID,
  updated_at TIMESTAMPTZ DEFAULT now(),
  organisation_id UUID
);

-- Enable RLS
ALTER TABLE fire_hazard_assessments ENABLE ROW LEVEL SECURITY;

-- Simple policy for now
CREATE POLICY "Allow all for authenticated users" ON fire_hazard_assessments
  FOR ALL USING (auth.role() = 'authenticated');